#spring:
#  thymeleaf:
#    prefix: classpath:/templates/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    #    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: loginserver
  #        jdbc:
  #          lob:
  #            non_contextual_creation: true
#  sql:
#    init:
#      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#errors:
#  error-page-url: "/denied"