spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
#  mvc:
#    static-path-pattern: /**


logging:
  level.org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE

