drop table if exists roles CASCADE;
drop table if exists user_role CASCADE;
drop table if exists users CASCADE;

create table roles
(
    id bigint generated by default as identity,
    role_name varchar(255),
    primary key (id)
);

create table user_role
(
    id      bigint generated by default as identity,
    role_id bigint,
    user_id bigint,
    primary key (id)
);

create table users
(
    id       bigint generated by default as identity,
    username varchar(255),
    primary key (id)
);

alter table user_role
    add constraint FKt7e7djp752sqn6w22i6ocqy6q
        foreign key (role_id)
            references roles;

alter table user_role
    add constraint FKj345gk1bovqvfame88rcx7yyx
        foreign key (user_id)
            references users;