#spring:
#  thymeleaf:
#    prefix: classpath:/templates/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=loginserver
    username: postgres
    password: postgres
  jpa:
    #    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  #        default_schema: loginservera
  #        jdbc:
  #          lob:
  #            non_contextual_creation: true
  #  sql:
  #    init:
  #      mode: always
  ## separate datasource for spring session
  session:
    store-type: jdbc
    jdbc:
      schema:
      table-name: SPRING_SESSION
      initialize-schema: never
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#errors:
#  error-page-url: "/denied"

## spring session exclusive data source
session:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_session
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

server:
  port: 8000